### PR TITLE
update license.txt and delete licensed-hardware.txt

### PR DESCRIPTION
**Pull request by wickste**
## PR checklist

- [x] Updated function header with a short description and version number
- [ ] Added test case for bug fix or new feature
- [ ] Validated on real hardware

### CODE REVIEW

**Review by timlt — APPROVED** [review]

**Review by williamelamie — APPROVED** [review]
MIT License update looks good

**Comment by jserv** [comment]
At present, `README.md` claims
> License terms for using ThreadX RTOS are defined in the LICENSE.txt file of this repo. Please refer to this file for all definitive licensing information. No additional license fees are required for deploying ThreadX RTOS on hardware defined in the LICENSED-HARDWARE.txt file. If you are using hardware not defined in the LICENSED-HARDWARE.txt file or have licensing questions in general, please contact Microsoft directly at https://aka.ms/azrtos-license.

The above seems to be outdated.

**Comment by wickste** [comment]
Yes, it's outdated. I am in the process of getting these updated. Please stay tuned as we are working through the transition.

Thanks,
Stefan

**Review by billlamiework — APPROVED** [review]
Change to MIT license looks good.

**Pull request merged**
